Repository Monest-eco/monest_mobile, pull requests merged in 2021-12, with the labels that each got.

#5 Create dart.yml
  .github/workflows/dart.yml
Labels: DevOps

#10 Started adapting the PC version
  .gitignore
  lib/main.dart
  lib/utils/responsive_widget.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, Mobile

#12 [feat/change_navbar] change color on navbar
  lib/main.dart
Labels: enhancement, Mobile, v1.x.x

#15 [feat/sidebar] add sidebar
  lib/main.dart
  lib/redirect.dart
  lib/sidebar.dart
Labels: Mobile

#22 Finished settings page
  assets/colors/Lessum_action_7.pdf
  ios/Flutter/Generated.xcconfig
  ios/Flutter/flutter_export_environment.sh
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/contents.xcworkspacedata
  lib/components/home_page/Home/bottom_app_bar.dart
  lib/components/home_page/Home/home.dart
  lib/components/home_page/Home/home_app_bar.dart
  lib/components/home_page/Settings/setting_app_bar.dart
  lib/components/home_page/Settings/setting_switch_body.dart
  lib/components/home_page/Settings/setting_title.dart
  lib/components/home_page/Settings/settings.dart
  lib/components/home_page/Settings/settings_body.dart
  lib/main.dart
  lib/pages/home_page.dart
  macos/Podfile.lock
  macos/Runner.xcodeproj/project.pbxproj
  macos/Runner.xcworkspace/contents.xcworkspacedata
Labels: enhancement, Mobile

#20 Display sidebar only for Laptop or tablette
  android/local.properties
  lib/components/home_page/Home/home.dart
  lib/components/home_page/Home/refresh_button_chart.dart
  lib/pages/home_page.dart
  web/favicon.png
  web/icons/Icon-192.png
  web/icons/Icon-512.png
  web/icons/Icon-maskable-192.png
  web/icons/Icon-maskable-512.png
  web/index.html
  web/manifest.json
Labels: Mobile

#28 Analysis Page | Cards to display devices
  android/local.properties
  ios/Flutter/Generated.xcconfig
  ios/Flutter/flutter_export_environment.sh
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  lib/components/analysis/analysis.dart
  lib/components/analysis/cards/cards.dart
  lib/components/home_page/Home/home.dart
  lib/components/sidebar/sidebar.dart
  lib/main.dart
  lib/pages/analysis_page.dart
  lib/pages/home_page.dart
  pubspec.lock
  pubspec.yaml
  web/index.html
Labels: Mobile
